// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.1";

// src/lib/mcp/tools/list-projects.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List projects",
  description: "List the construction projects the signed-in user can access, with status and completion.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(25).describe("Maximum number of projects to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Sign in to list projects.");
    const { data, error } = await supabaseForUser(ctx).from("projects").select("id, code, title, status, completion, location, start_date, planned_end_date, current_phase").order("created_at", { ascending: false }).limit(limit);
    if (error) throw new ToolError(error.message);
    const projects = (data ?? []).map((p) => ({
      id: p.id,
      code: p.code,
      title: p.title,
      status: p.status,
      completion: p.completion,
      location: p.location,
      startDate: p.start_date,
      plannedEndDate: p.planned_end_date,
      currentPhase: p.current_phase
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(projects, null, 2) }],
      structuredContent: { projects }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project overview",
  description: "Get one project with its milestones and progress for the signed-in user.",
  inputSchema: {
    project_id: z2.string().uuid().describe("The project identifier.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Sign in to read a project.");
    const supabase = supabaseForUser(ctx);
    const { data: project, error } = await supabase.from("projects").select("id, code, title, status, completion, location, type, start_date, planned_end_date, current_phase, client_name, entreprise, mission_controle").eq("id", project_id).maybeSingle();
    if (error) throw new ToolError2(error.message);
    if (!project) throw new ToolError2("Project not found or not visible to you.");
    const { data: milestoneRows, error: mErr } = await supabase.from("milestones").select("id, title, status, progress, review_status, is_published, planned_start, planned_end, ordering").eq("project_id", project_id).order("ordering", { ascending: true });
    if (mErr) throw new ToolError2(mErr.message);
    const result = {
      id: project.id,
      code: project.code,
      title: project.title,
      status: project.status,
      completion: project.completion,
      location: project.location,
      type: project.type,
      startDate: project.start_date,
      plannedEndDate: project.planned_end_date,
      currentPhase: project.current_phase,
      clientName: project.client_name,
      entreprise: project.entreprise,
      missionControle: project.mission_controle,
      milestones: (milestoneRows ?? []).map((m) => ({
        id: m.id,
        title: m.title,
        status: m.status,
        progress: m.progress,
        reviewStatus: m.review_status,
        isPublished: m.is_published,
        plannedStart: m.planned_start,
        plannedEnd: m.planned_end,
        ordering: m.ordering
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { project: result }
    };
  }
});

// src/lib/mcp/tools/list-reports.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_reports_default = defineTool3({
  name: "list_reports",
  title: "List site reports",
  description: "List daily and weekly site journal reports for a project, with their workflow state.",
  inputSchema: {
    project_id: z3.string().uuid().describe("The project identifier."),
    report_type: z3.enum(["daily", "weekly", "all"]).default("all").describe("Filter by journal type."),
    limit: z3.number().int().min(1).max(100).default(20).describe("Maximum number of reports to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, report_type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Sign in to list reports.");
    let query = supabaseForUser(ctx).from("daily_reports").select("id, report_ref, report_type, report_date, week_start, week_end, state, status, is_published, is_late, title, summary").eq("project_id", project_id).order("report_date", { ascending: false }).limit(limit);
    if (report_type !== "all") query = query.eq("report_type", report_type);
    const { data, error } = await query;
    if (error) throw new ToolError3(error.message);
    const reports = (data ?? []).map((r) => ({
      id: r.id,
      ref: r.report_ref,
      type: r.report_type,
      date: r.report_date,
      weekStart: r.week_start,
      weekEnd: r.week_end,
      state: r.state,
      status: r.status,
      isPublished: r.is_published,
      isLate: r.is_late,
      title: r.title,
      summary: r.summary
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(reports, null, 2) }],
      structuredContent: { reports }
    };
  }
});

// src/lib/mcp/tools/get-report.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z4 } from "npm:zod@^3.25.76";
var get_report_default = defineTool4({
  name: "get_report",
  title: "Get site report",
  description: "Read the full content of one daily or weekly site journal report.",
  inputSchema: {
    report_id: z4.string().uuid().describe("The report identifier.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ report_id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Sign in to read a report.");
    const { data, error } = await supabaseForUser(ctx).from("daily_reports").select(
      "id, project_id, report_ref, report_type, report_date, week_start, week_end, state, status, is_published, is_late, title, summary, weather, work_area, work_start_time, work_end_time, workforce_count, achievements, challenges, delays, corrective_actions, safety_observations, technical_observations, supervision_instructions, owner_instructions, next_plan, notes, submitted_at_server, reviewed_at, published_at"
    ).eq("id", report_id).maybeSingle();
    if (error) throw new ToolError4(error.message);
    if (!data) throw new ToolError4("Report not found or not visible to you.");
    const report = {
      id: data.id,
      projectId: data.project_id,
      ref: data.report_ref,
      type: data.report_type,
      date: data.report_date,
      weekStart: data.week_start,
      weekEnd: data.week_end,
      state: data.state,
      status: data.status,
      isPublished: data.is_published,
      isLate: data.is_late,
      title: data.title,
      summary: data.summary,
      weather: data.weather,
      workArea: data.work_area,
      workStartTime: data.work_start_time,
      workEndTime: data.work_end_time,
      workforceCount: data.workforce_count,
      achievements: data.achievements,
      challenges: data.challenges,
      delays: data.delays,
      correctiveActions: data.corrective_actions,
      safetyObservations: data.safety_observations,
      technicalObservations: data.technical_observations,
      supervisionInstructions: data.supervision_instructions,
      ownerInstructions: data.owner_instructions,
      nextPlan: data.next_plan,
      notes: data.notes,
      submittedAt: data.submitted_at_server,
      reviewedAt: data.reviewed_at,
      publishedAt: data.published_at
    };
    return {
      content: [{ type: "text", text: JSON.stringify(report, null, 2) }],
      structuredContent: { report }
    };
  }
});

// src/lib/mcp/tools/list-issues.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_issues_default = defineTool5({
  name: "list_issues",
  title: "List site issues",
  description: "List issues raised on a project, with severity and status.",
  inputSchema: {
    project_id: z5.string().uuid().describe("The project identifier."),
    status: z5.enum(["open", "in-progress", "resolved", "all"]).default("all").describe("Filter by issue status."),
    limit: z5.number().int().min(1).max(100).default(25).describe("Maximum number of issues to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError5("Sign in to list issues.");
    let query = supabaseForUser(ctx).from("report_issues").select("id, title, description, impact, severity, status, date_identified, is_published").eq("project_id", project_id).order("date_identified", { ascending: false }).limit(limit);
    if (status !== "all") query = query.eq("status", status);
    const { data, error } = await query;
    if (error) throw new ToolError5(error.message);
    const issues = (data ?? []).map((i) => ({
      id: i.id,
      title: i.title,
      description: i.description,
      impact: i.impact,
      severity: i.severity,
      status: i.status,
      dateIdentified: i.date_identified,
      isPublished: i.is_published
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(issues, null, 2) }],
      structuredContent: { issues }
    };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { defineTool as defineTool6, ToolError as ToolError6 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_tasks_default = defineTool6({
  name: "list_my_tasks",
  title: "List my tasks",
  description: "List the tasks assigned to the signed-in user, newest first.",
  inputSchema: {
    project_id: z6.string().uuid().optional().describe("Optionally restrict to one project."),
    limit: z6.number().int().min(1).max(100).default(25).describe("Maximum number of tasks to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError6("Sign in to list your tasks.");
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError6("Could not determine the signed-in user.");
    let query = supabaseForUser(ctx).from("tasks").select("id, project_id, title, description, status, priority, due_date, milestone_id, sub_milestone_id").eq("assigned_to", userId).order("due_date", { ascending: true }).limit(limit);
    if (project_id) query = query.eq("project_id", project_id);
    const { data, error } = await query;
    if (error) throw new ToolError6(error.message);
    const tasks = (data ?? []).map((t) => ({
      id: t.id,
      projectId: t.project_id,
      title: t.title,
      description: t.description,
      status: t.status,
      priority: t.priority,
      dueDate: t.due_date,
      milestoneId: t.milestone_id,
      subMilestoneId: t.sub_milestone_id
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(tasks, null, 2) }],
      structuredContent: { tasks }
    };
  }
});

// src/lib/mcp/tools/create-issue.ts
import { defineTool as defineTool7, ToolError as ToolError7 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z7 } from "npm:zod@^3.25.76";
var create_issue_default = defineTool7({
  name: "create_issue",
  title: "Create site issue",
  description: "Raise a new issue on a project as the signed-in user. The issue starts unpublished and open.",
  inputSchema: {
    project_id: z7.string().uuid().describe("The project identifier."),
    title: z7.string().trim().min(1).max(200).describe("Short issue title."),
    description: z7.string().trim().max(4e3).optional().describe("Detailed description of the issue."),
    impact: z7.string().trim().max(2e3).optional().describe("Impact on cost, schedule or quality."),
    severity: z7.enum(["low", "medium", "high", "critical"]).default("medium").describe("Issue severity.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ project_id, title, description, impact, severity }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError7("Sign in to create an issue.");
    const userId = ctx.getUserId();
    if (!userId) throw new ToolError7("Could not determine the signed-in user.");
    const { data, error } = await supabaseForUser(ctx).from("report_issues").insert({
      project_id,
      title,
      description: description ?? null,
      impact: impact ?? null,
      severity,
      created_by: userId
    }).select("id, title, severity, status, date_identified").maybeSingle();
    if (error) throw new ToolError7(error.message);
    if (!data) throw new ToolError7("The issue could not be created.");
    const issue = {
      id: data.id,
      title: data.title,
      severity: data.severity,
      status: data.status,
      dateIdentified: data.date_identified
    };
    return {
      content: [{ type: "text", text: `Created issue "${issue.title}" (${issue.severity}).` }],
      structuredContent: { issue }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tjpdvjphfyjmluxhlrzu";
var mcp_default = defineMcp({
  name: "buildtrust-app",
  title: "BuildTrust App",
  version: "0.1.0",
  instructions: "Tools for BuildTrust, a construction transparency platform. Use `list_projects` to find projects, `get_project` for milestones and progress, `list_reports`/`get_report` for daily and weekly site journals, `list_issues` and `create_issue` for site issues, and `list_my_tasks` for the signed-in user's assignments. All data is scoped to the signed-in user's permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_projects_default,
    get_project_default,
    list_reports_default,
    get_report_default,
    list_issues_default,
    list_tasks_default,
    create_issue_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
